/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyekkasiralfacom;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HALIM
 */
public class HalamanKasirForm extends javax.swing.JFrame {
    private final DefaultTableModel modelKeranjang;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HalamanKasirForm.class.getName());

    /**
     * Creates new form HalamanKasirForm
     */
    public HalamanKasirForm() {
        initComponents();
        loadData();
        setLocationRelativeTo(null);
        
        modelKeranjang = new DefaultTableModel(
                new Object[]{"Kode", "Nama", "Harga", "jumlah", "Subtotal"}, 0);
        tabelKanan.setModel(modelKeranjang);
        hitungTotal();

    }
    private void loadData() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Kode");
    model.addColumn("Nama Barang");
    model.addColumn("Deskripsi");
    model.addColumn("Kategori");
    model.addColumn("Harga Jual");
    model.addColumn("Stok");
    model.addColumn("Satuan");
    model.addColumn("Status");

    try {
        Connection conn = Koneksi.getKoneksi();

        String sql = """
            SELECT 
                p.kode_barang,
                p.nama_barang,
                p.deskripsi,
                k.nama_kategori AS kategori,
                p.harga_jual,
                p.stok,
                s.nama_satuan AS satuan,
                p.status
            FROM products p
            LEFT JOIN kategori k ON p.kategori_id = k.id
            LEFT JOIN satuan s ON p.satuan_id = s.id
        """;

        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery(sql);

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("kode_barang"),
                rs.getString("nama_barang"),
                rs.getString("deskripsi"),
                rs.getString("kategori"),
                rs.getString("harga_jual"),
                rs.getString("stok"),
                rs.getString("satuan"),
                rs.getString("status")
            });
        }
        tabelKiri.setModel(model);

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Load data gagal: " + e.getMessage());}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelKiri = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelKanan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtCariProduk = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnCari = new javax.swing.JButton();
        btnCekout = new javax.swing.JButton();
        tbltotal = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnTambahKeranjang = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(214, 217, 224));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        tabelKiri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelKiri);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 438;
        gridBagConstraints.ipady = 287;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 0, 0);
        jPanel1.add(jScrollPane1, gridBagConstraints);

        tabelKanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabelKanan);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 346;
        gridBagConstraints.ipady = 287;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        jPanel1.add(jScrollPane2, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("DAFTAR PRODUK");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = -15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 92;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 12, 0, 0);
        jPanel1.add(txtCariProduk, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("CARI PRODUK");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = -15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 0, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        btnCari.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCari.setText("CARI");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 18, 0, 0);
        jPanel1.add(btnCari, gridBagConstraints);

        btnCekout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCekout.setText("CHECKOUT");
        btnCekout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekoutActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 237;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(39, 17, 0, 0);
        jPanel1.add(btnCekout, gridBagConstraints);

        tbltotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbltotal.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 0);
        jPanel1.add(tbltotal, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Keranjang Belanja");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 3, 0, 0);
        jPanel1.add(jLabel5, gridBagConstraints);

        btnTambahKeranjang.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnTambahKeranjang.setText("Tambahkan Keranjang");
        btnTambahKeranjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahKeranjangActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = -11;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 6, 0, 0);
        jPanel1.add(btnTambahKeranjang, gridBagConstraints);

        btnKembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(39, 0, 0, 0);
        jPanel1.add(btnKembali, gridBagConstraints);

        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 6, 0, 0);
        jPanel1.add(btnHapus, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 776, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCekoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekoutActionPerformed
        if (modelKeranjang.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Keranjang kosong!");
            return;}
        Cekoutform c = new Cekoutform(modelKeranjang);
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCekoutActionPerformed

    private void btnTambahKeranjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahKeranjangActionPerformed
        int row = tabelKiri.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih produk dulu!");
            return;}
        String kode = tabelKiri.getValueAt(row, 0).toString();
        String nama = tabelKiri.getValueAt(row, 1).toString();
        int harga = Integer.parseInt(tabelKiri.getValueAt(row, 4).toString());
        int stok = Integer.parseInt(tabelKiri.getValueAt(row, 5).toString()); // ⬅ AMBIL STOK
        String qtyStr = JOptionPane.showInputDialog(this, "Masukkan jumlah:");
        if (qtyStr == null) return;
        int qty = Integer.parseInt(qtyStr);
// VALIDASI STOK
        if (qty > stok) {
            JOptionPane.showMessageDialog(this,
                    "Stok tidak mencukupi!\nStok tersedia: " + stok,
        "Peringatan",JOptionPane.WARNING_MESSAGE);
    return;}
        int subtotal = harga * qty;

// CEK JIKA PRODUK SUDAH ADA DI KERANJANG
for (int i = 0; i < modelKeranjang.getRowCount(); i++) {
    if (modelKeranjang.getValueAt(i, 0).toString().equals(kode)) {
        int qtyLama = Integer.parseInt(modelKeranjang.getValueAt(i, 3).toString());
        int qtyBaru = qtyLama + qty;
        // CEK STOK TOTAL
        if (qtyBaru > stok) {
            JOptionPane.showMessageDialog(
                this,
                "Jumlah melebihi stok!\nStok tersedia: " + stok,
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;}
        int subBaru = qtyBaru * harga;
        modelKeranjang.setValueAt(qtyBaru, i, 3);
        modelKeranjang.setValueAt(subBaru, i, 4);
        // KURANGI STOK DI TABEL KIRI
        hitungTotal();
        return;}}
// TAMBAH BARIS BARU KE KERANJANG
modelKeranjang.addRow(new Object[]{
    kode, nama, harga, qty, subtotal});
// KURANGI STOK DI TABEL KIRI
hitungTotal();
    }//GEN-LAST:event_btnTambahKeranjangActionPerformed

private void hitungTotal() {
    int total = 0;
    DefaultTableModel model = (DefaultTableModel) tabelKanan.getModel();
    for (int i = 0; i < model.getRowCount(); i++) {
        total += Integer.parseInt(model.getValueAt(i, 4).toString());}
    tbltotal.setText("Total : Rp " + total); }

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
    new BerandaKasir().setVisible(true); 
    dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
String keyword = txtCariProduk.getText();

    DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Kode");
        model.addColumn("Nama Barang");
        model.addColumn("Deskripsi");
        model.addColumn("Kategori");
        model.addColumn("Harga Jual");
        model.addColumn("Stok");
        model.addColumn("Satuan");
        model.addColumn("Status");

    try {
        String sql = """
        SELECT 
            p.kode_barang,
            p.nama_barang,
            p.deskripsi,
            k.nama_kategori AS kategori,
            p.harga_jual,
            p.stok,
            s.nama_satuan AS satuan,
            p.status
        FROM products p
        LEFT JOIN kategori k ON p.kategori_id = k.id
        LEFT JOIN satuan s ON p.satuan_id = s.id
        WHERE p.nama_barang LIKE '%""" + keyword + "%'";

        Connection conn = Koneksi.getKoneksi();
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery(sql);

        while (rs.next()) {
            model.addRow(new Object[]{
                    rs.getString("kode_barang"),
                    rs.getString("nama_barang"),
                    rs.getString("deskripsi"),
                    rs.getString("kategori"),
                    rs.getString("harga_jual"),
                    rs.getString("stok"),
                    rs.getString("satuan"),
                    rs.getString("status")
            });
        }
        tabelKiri.setModel(model);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());}                                            
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed

int rowKeranjang = tabelKanan.getSelectedRow();
    if (rowKeranjang == -1) {
        JOptionPane.showMessageDialog(this, "Pilih item di keranjang!");
        return;
    }

    modelKeranjang.removeRow(rowKeranjang);
    hitungTotal();
    }//GEN-LAST:event_btnHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HalamanKasirForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnCekout;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnTambahKeranjang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelKanan;
    private javax.swing.JTable tabelKiri;
    private javax.swing.JLabel tbltotal;
    private javax.swing.JTextField txtCariProduk;
    // End of variables declaration//GEN-END:variables
}
